---
title: "Name Exploration"
author: "Rose Porta"
date: '2022-05-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
minifigs_data <- read_csv("minifigs_data.csv")

minifigs_data2 <- minifigs_data |> 
  filter(str_detect(description, "Diva") | 
           str_detect(description, "Lady") |
           str_detect(description, "Girl") |
           str_detect(description, "Female") |
           str_detect(description, "Woman") |
           str_detect(description, "Maiden") |
           str_detect(description, "Starlet")
           )

# top 5 categories containing explicity defined women/girl minifigs
minifigs_data2_counts <- minifigs_data2 |> 
  group_by(category) |> 
  summarize(count = n()) |> 
  top_n(n = 5)

ggplot(minifigs_data2_counts, aes(x = reorder(category, count), fill = category, y = count)) +
  geom_col() +
  coord_flip()
```

```{r}
scrape_year <- function(url) {
  if (!robotstxt::paths_allowed(paths = c(url))) stop("scraping not allowed, cannot proceed")
  item_page <- rvest::read_html(url)
  release_year <- item_page |> 
    html_elements("#yearReleasedSec") |> 
    html_text()
  release_year
}
```

```{r}
year <- map(minifigs_data2$item_link, scrape_year)
year <- year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .) |> 
  as.numeric()

minifigs_data2 <- minifigs_data2 |> 
  mutate(year = year)

write_csv(minifigs_data2, file = "female.csv")
```

```{r}
minifigs_data2_year <- minifigs_data2 |> 
  filter(!is.na(year)) |> 
  group_by(year) |> 
  summarize(count = n())

ggplot(minifigs_data2_year, aes(x = year, y = count)) +
  geom_line() +
  labs(title = "Number of Female-Specified Minifigs by Year",
       y = "Number of Female-Specified Minifigs Released")
```

# Starwars

```{r}
minifigs_starwars <- minifigs_data |> 
  filter(category == "Star Wars")
minifig_characters <- tolower(minifigs_starwars$description)
movie_characters <- tolower(starwars$name)

num_minifigs <- map_int(movie_characters, ~sum(str_detect(minifig_characters, .x)))

starwars_minifigs_compare <- starwars |> 
  select(name, sex, species, films) |> 
  mutate(num_minifigs = num_minifigs,
         num_films = map_int(films, length),
         ratio = num_minifigs/num_films
         )

```

```{r}
ggplot(starwars_minifigs_compare,
       aes(x = num_films, y = num_minifigs, color = sex)) +
  geom_point() +
  geom_jitter() +
  scale_color_wbi() +
  labs(title = "Relationship between Number of Films and Number of Minifigs by Sex")
```

```{r}
sw_mf2 <- starwars_minifigs_compare |> 
  group_by(sex) |> 
  summarize(mean_films = mean(num_films), mean_minifigs = mean(num_minifigs)) |> 
  filter(!is.na(sex)) |> 
  pivot_longer(
    cols = c(mean_films, mean_minifigs), names_to = "comp", values_to = "average_num")

ggplot(sw_mf2, aes(x = reorder(sex, desc(average_num)), y = average_num, fill = comp)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_wbi() +
  labs(title = "Comparison of Films and Minifigs by Sex",
       x = "sex")
  
```

```{r}
sw_mf_ratio <- starwars_minifigs_compare |> 
  group_by(sex) |> 
  summarize(mean_ratio = mean(ratio)) |> 
  filter(!is.na(sex)) |> 
  filter(mean_ratio > 0)

ggplot(sw_mf_ratio, aes(x = reorder(sex, desc(mean_ratio)), y = mean_ratio, fill = sex)) +
  geom_col() +
  scale_fill_wbi() +
  labs(title = "Ratio of Number of Minifigs to Number of Films by Sex",
       x = "sex")
```

