---
title: "professions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
prof_data <- read_csv(here::here("data", "town_minifig.csv"))
source(here::here("wbi_colors.R"))
```

```{r}
town_data <- prof_data |>
  # filter(category=="Town") |>
  mutate(gender = case_when(
    str_detect(description, "Male") |
      str_detect(tolower(description), "beard") |
      str_detect(tolower(description), "goatee") |
      str_detect(tolower(description), "sideburns") |
      str_detect(tolower(description), "moustache") |
      str_detect(tolower(description), "stubble") |
      str_detect(description, "Man") |
      str_detect(tolower(description), "businessman")
    ~ "male",
    str_detect(description, "Female") |
      str_detect(tolower(description), "eyelashes") |
      str_detect(tolower(description), "ponytail") |
      str_detect(tolower(description), "pigtails") |
      str_detect(tolower(description), "lips") |
      str_detect(tolower(description), "girl") |
      str_detect(tolower(description), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  mutate(item_link = paste0("https://bricklink.com/v2/catalog/catalogitem.page?M=", item_number)) |>
  mutate(parts_link = paste0("https://www.bricklink.com/catalogItemInv.asp?M=", item_number))
```

```{r}
doctor <- town_data |>
  filter(str_detect(tolower(description), "doctor")) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of doctor counts
g1 <- ggplot(doctor, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Doctor",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g1
g1 <- add_logo(g1)

# Bar chart of doctor proportions
g2 <- ggplot(doctor, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Doctor",
    subtitle = paste("Out of", as.character(sum(doctor$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g2
g2 <- add_logo(g2)
```

```{r}
police <- town_data |>
  filter(
    str_detect(tolower(description), "police"),
    !str_detect(tolower(description), "jail"),
    !str_detect(tolower(description), "crook")
  ) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of police counts
g3 <- ggplot(police, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Police",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g3
g3 <- add_logo(g3)

# Bar chart of police proportions
g4 <- ggplot(police, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Police",
    subtitle = paste("Out of", as.character(sum(police$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g4
g4 <- add_logo(g4)
```

```{r}
business <- town_data |>
  filter(str_detect(tolower(description), "business")) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of businessperson counts
g5 <- ggplot(business, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Businessperson",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g5
g5 <- add_logo(g5)

# Bar chart of businessperson proportions
g6 <- ggplot(business, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Businessperson",
    subtitle = paste("Out of", as.character(sum(business$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g6
g6 <- add_logo(g6)
```

```{r}
scientist <- town_data |>
  filter(str_detect(tolower(description), "scientist")) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of scientist counts
g7 <- ggplot(scientist, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Scientist",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g7
g7 <- add_logo(g7)

# Bar chart of scientist proportions
g8 <- ggplot(scientist, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Scientist",
    subtitle = paste("Out of", as.character(sum(scientist$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g8
g8 <- add_logo(g8)
```

```{r}
astronaut <- town_data |>
  filter(str_detect(tolower(description), "astronaut")) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of astronaut counts
g9 <- ggplot(astronaut, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Astronaut",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g9
g9 <- add_logo(g9)

# Bar chart of astronaut proportions
g10 <- ggplot(astronaut, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Astronaut",
    subtitle = paste("Out of", as.character(sum(astronaut$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g10
g10 <- add_logo(g10)
```

```{r}
chef <- town_data |>
  filter(str_detect(tolower(description), "chef")) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of chef counts
g11 <- ggplot(chef, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Chef",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g11
g11 <- add_logo(g11)

# Bar chart of chef proportions
g12 <- ggplot(chef, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Chef",
    subtitle = paste("Out of", as.character(sum(chef$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g12
g12 <- add_logo(g12)
```

```{r}
pilot <- town_data |>
  filter(
    str_detect(tolower(description), "pilot"),
    !str_detect(tolower(description), "police")
  ) |>
  mutate(total = n()) |>
  group_by(gender) |>
  summarize(count = n(), prop = round(count / total, 2)) |>
  distinct()

# Bar chart of pilot counts
g13 <- ggplot(pilot, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Pilot",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
g13
g13 <- add_logo(g13)

# Bar chart of pilot proportions
g14 <- ggplot(pilot, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Pilot",
    subtitle = paste("Out of", as.character(sum(pilot$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
g14
g14 <- add_logo(g14)
```

```{r}
names <- c("g1.png", "g2.png", "g3.png", "g4.png", "g5.png", "g6.png", "g7.png", "g8.png", "g9.png", "g10.png", "g11.png", "g12.png", "g13.png", "g14.png")
plots <- list(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14)

map2(names, plots, ggsave)
```

```{r}
# function to scrape release year given item link
scrape_year <- function(url) {
  if (!robotstxt::paths_allowed(paths = c(url))) stop("scraping not allowed, cannot proceed")
  item_page <- rvest::read_html(url)
  release_year <- item_page |> 
    html_elements("#yearReleasedSec") |> 
    html_text()
  release_year
}

# function to scrape parts description given item link
scrape_parts_description <- function(url){
  item_page <- rvest::read_html(url)
  parts_description <- item_page |> 
    html_elements(".IV_ITEM td:nth-child(4) b") |> 
    html_text()
  parts_description
}
```

```{r}
# filter to only police and add links to items (minifigs) and parts
police_release_year <- town_data |>
  filter(
    str_detect(tolower(description), "police"),
    !str_detect(tolower(description), "jail"),
    !str_detect(tolower(description), "crook")
  ) |> 
  mutate(item_link = paste0("https://bricklink.com/v2/catalog/catalogitem.page?M=", item_number)) |>
  mutate(parts_link = paste0("https://www.bricklink.com/catalogItemInv.asp?M=", item_number))
```

```{r}
# Filter to "no tag" only
police_notag <- police_release_year |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(police_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
police_notag <- police_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (police2)
police2 <- police_release_year |> 
  filter(gender != "no tag") |> 
  mutate(item_link = paste0("https://bricklink.com/v2/catalog/catalogitem.page?M=", item_number)) |>
  mutate(parts_link = paste0("https://www.bricklink.com/catalogItemInv.asp?M=", item_number)) |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(police_notag)

# Scrape release_year
release_year <- map(police2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to police2 dataframe and convert to numeric
police2 <- police2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year))

# Filter to only female
policewomen <- police2 |> 
  filter(gender2=="female") |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year))

# Summarize counts and props by gender2 for graphing
police2_graph <- police2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of police2 counts
p1 <- ggplot(police2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Police Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
p1
p1 <- add_logo(p1)

# Bar chart of police2 proportions
p2 <- ggplot(police2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Police Corrected",
    subtitle = paste("Out of", as.character(sum(police2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
p2
p2 <- add_logo(p2)

# Histogram of police2 counts
p3 <- ggplot(police2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Police Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
p3
p3 <- add_logo(p3)
```

```{r}
names <- c("p1.png", "p2.png", "p3.png")
plots <- list(p1, p2, p3)

map2(names, plots, ggsave)

```

### Chef

```{r}
# filter to only chef and add links to items (minifigs) and parts
chef_release_year <- town_data |>
  filter(str_detect(tolower(description), "chef"))
```

```{r}
# Filter to "no tag" only
chef_notag <- chef_release_year |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(chef_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
chef_notag <- chef_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (police2)
chef2 <- chef_release_year |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(chef_notag)

# Scrape release_year
release_year <- map(chef2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to chef2 dataframe and convert to numeric
chef2 <- chef2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year)) |> 
  mutate(gender2=ifelse(release_year<1998, "male", gender2))

# Summarize counts and props by gender2 for graphing
chef2_graph <- chef2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of chef2 counts
c1 <- ggplot(chef2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Chef Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
c1
c1 <- add_logo(c1)

# Bar chart of chef2 proportions
c2 <- ggplot(chef2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Chef Corrected",
    subtitle = paste("Out of", as.character(sum(chef2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
c2
c2 <- add_logo(c2)

# Histogram of chef2 counts
c3 <- ggplot(chef2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Chef Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
c3
c3 <- add_logo(c3)
```

```{r}
names <- c("c1.png", "c2.png", "c3.png")
plots <- list(c1, c2, c3)

map2(names, plots, ggsave)

```

### Diver

```{r}
# filter to only diver and add links to items (minifigs) and parts
diver <- town_data |>
  filter(str_detect(tolower(description), "diver"))
```

```{r}
# Filter to "no tag" only
diver_notag <- diver |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(diver_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
diver_notag <- diver_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (diver2)
diver2 <- diver |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(diver_notag)

# Scrape release_year
release_year <- map(diver2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to diver2 dataframe and convert to numeric
diver2 <- diver2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year)) |> 
  mutate(gender2=ifelse(release_year<1998, "male", gender2))

# Summarize counts and props by gender for graphing
diver_graph <- diver |> 
  mutate(total=n()) |> 
  group_by(gender) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()

# Summarize counts and props by gender2 for graphing
diver2_graph <- diver2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of diver2 counts
d0 <- ggplot(diver_graph, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Diver",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
d0
d0 <- add_logo(d0)

d1 <- ggplot(diver2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Diver Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
d1
d1 <- add_logo(d1)

# Bar chart of chef2 proportions
d0b <- ggplot(diver_graph, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Diver",
    subtitle = paste("Out of", as.character(sum(diver2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
d0b
d0b <- add_logo(d0b)

d2 <- ggplot(diver2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Diver Corrected",
    subtitle = paste("Out of", as.character(sum(diver2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
d2
d2 <- add_logo(d2)

# Histogram of diver2 counts
d3 <- ggplot(diver2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Diver Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
d3
d3 <- add_logo(d3)
```

```{r}
names <- c("d0.png", "d1.png", "d0b.png", "d2.png", "d3.png")
plots <- list(d0, d1, d0b, d2, d3)

map2(names, plots, ggsave)

```

### Driver

```{r}
# filter to only driver and add links to items (minifigs) and parts
driver <- town_data |>
  filter(str_detect(tolower(description), "driver"))
```

```{r}
# Filter to "no tag" only
driver_notag <- driver |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(driver_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
driver_notag <- driver_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (diver2)
driver2 <- driver |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(driver_notag)

# Scrape release_year
release_year <- map(driver2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to diver2 dataframe and convert to numeric
driver2 <- driver2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year)) |> 
  mutate(gender2=ifelse(release_year<2000, "male", gender2))

# Summarize counts and props by gender for graphing
driver_graph <- driver |> 
  mutate(total=n()) |> 
  group_by(gender) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()

# Summarize counts and props by gender2 for graphing
driver2_graph <- driver2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of driver counts
dr0 <- ggplot(driver_graph, aes(x = gender, y = count, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Driver",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
dr0
dr0 <- add_logo(d0)

dr1 <- ggplot(driver2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Driver Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
dr1
dr1 <- add_logo(dr1)

# Bar chart of driver2 proportions
dr0b <- ggplot(driver_graph, aes(x = gender, y = prop, fill = gender)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Driver",
    subtitle = paste("Out of", as.character(sum(driver2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
dr0b
dr0b <- add_logo(dr0b)

dr2 <- ggplot(driver2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Driver Corrected",
    subtitle = paste("Out of", as.character(sum(driver2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
dr2
dr2 <- add_logo(dr2)

# Histogram of driver2 counts
dr3 <- ggplot(driver2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Driver Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
dr3
dr3 <- add_logo(dr3)
```

```{r}
names <- c("dr0.png", "dr1.png", "dr0b.png", "dr2.png", "dr3.png")
plots <- list(dr0, dr1, dr0b, dr2, dr3)

map2(names, plots, ggsave)

```

### Doctor

```{r}
# filter to only doctor and add links to items (minifigs) and parts
doctor <- town_data |>
  filter(str_detect(tolower(description), "doctor"))
```

```{r}
# Filter to "no tag" only
doctor_notag <- doctor |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(doctor_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
doctor_notag <- doctor_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new doctor dataframe with re-categorized gender (doctor2)
doctor2 <- doctor |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(doctor_notag)

# Scrape release_year
release_year <- map(doctor2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to chef2 dataframe and convert to numeric
doctor2 <- doctor2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year))

# Summarize counts and props by gender2 for graphing
doctor2_graph <- doctor2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of doctor2 counts
doc1 <- ggplot(doctor2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Doctor Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
doc1
doc1 <- add_logo(doc1)

# Bar chart of chef2 proportions
doc2 <- ggplot(doctor2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Doctor Corrected",
    subtitle = paste("Out of", as.character(sum(doctor2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
doc2
doc2 <- add_logo(doc2)

# Histogram of chef2 counts
doc3 <- ggplot(doctor2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Doctor Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
doc3
doc3 <- add_logo(doc3)
```

```{r}
names <- c("doc1.png", "doc2.png", "doc3.png")
plots <- list(doc1, doc2, doc3)

map2(names, plots, ggsave)

```

### Astronaut

```{r}
# filter to only chef and add links to items (minifigs) and parts
astronaut <- town_data |>
  filter(str_detect(tolower(description), "astronaut"))
```

```{r}
# Filter to "no tag" only
astronaut_notag <- astronaut |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(astronaut_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
astronaut_notag <- astronaut_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (astronaut2)
astronaut2 <- astronaut |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(astronaut_notag)

# Scrape release_year
release_year <- map(astronaut2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to astronaut2 dataframe and convert to numeric
astronaut2 <- astronaut2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year)) |> 
  mutate(gender2=ifelse(release_year<1999, "male", gender2))

# Summarize counts and props by gender2 for graphing
astronaut2_graph <- astronaut2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of astronaut2 counts
a1 <- ggplot(astronaut2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Astronaut Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
a1
a1 <- add_logo(a1)

# Bar chart of astronaut2 proportions
a2 <- ggplot(astronaut2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Astronaut Corrected",
    subtitle = paste("Out of", as.character(sum(astronaut2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
a2
a2 <- add_logo(a2)

# Histogram of astronaut2 counts
a3 <- ggplot(astronaut2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Astronaut Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
a3
a3 <- add_logo(a3)
```

```{r}
names <- c("a1.png", "a2.png", "a3.png")
plots <- list(a1, a2, a3)

map2(names, plots, ggsave)

```

### Businessperson

```{r}
# filter to only business and add links to items (minifigs) and parts
business <- town_data |>
  filter(str_detect(tolower(description), "business"))
```

```{r}
# Filter to "no tag" only
business_notag <- business |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(business_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
business_notag <- business_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (police2)
business2 <- business |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(business_notag)

# Scrape release_year
release_year <- map(business2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to chef2 dataframe and convert to numeric
business2 <- business2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year))

# No changes, so no new graphs
```

### Scientist

```{r}
# filter to only scientist and add links to items (minifigs) and parts
scientist <- town_data |>
  filter(str_detect(tolower(description), "scientist"))
```

```{r}
# Filter to "no tag" only
scientist_notag <- scientist |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(scientist_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
scientist_notag <- scientist_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (scientist2)
scientist2 <- scientist |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(scientist_notag)

# Scrape release_year
release_year <- map(scientist2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to scientist2 dataframe and convert to numeric
scientist2 <- scientist2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year))

# Summarize counts and props by gender2 for graphing
scientist2_graph <- scientist2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of scientist2 counts
s1 <- ggplot(scientist2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Scientist Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
s1
s1 <- add_logo(s1)

# Bar chart of scientist2 proportions
s2 <- ggplot(scientist2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Scientist Corrected",
    subtitle = paste("Out of", as.character(sum(scientist2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
s2
s2 <- add_logo(s2)

# Histogram of scientist2 counts
s3 <- ggplot(scientist2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Scientist Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
s3
s3 <- add_logo(s3)
```

### Pilot

```{r}
# filter to only pilot and add links to items (minifigs) and parts
pilot <- town_data |>
  filter(str_detect(tolower(description), "pilot"))
```

```{r}
# Filter to "no tag" only
pilot_notag <- pilot |> 
  filter(gender=="no tag")

# Scrape parts descriptions for no-tag items/minifigs
parts_descriptions <- map(pilot_notag$parts_link, scrape_parts_description)

# Add parts descriptions as a column to dataframe
# Combine all parts' descriptions to one string for each minifig (temp)
# Re-categorize gender based on parts descriptions (gender2)
pilot_notag <- pilot_notag |> 
  mutate(parts_description = parts_descriptions) |> 
  mutate(temp = map_chr(parts_description, ~paste(.x, sep=" ", collapse=""))) |> 
  mutate(gender2 = case_when(
    str_detect(temp, "Male") |
      str_detect(tolower(temp), "beard") |
      str_detect(tolower(temp), "goatee") |
      str_detect(tolower(temp), "sideburns") |
      str_detect(tolower(temp), "moustache") |
      str_detect(tolower(temp), "stubble") |
      str_detect(temp, "Man") |
      str_detect(tolower(temp), "businessman")
    ~ "male",
      str_detect(temp, "Female") |
      str_detect(tolower(temp), "eyelashes") |
      str_detect(tolower(temp), "ponytail") |
      str_detect(tolower(temp), "pigtails") |
      str_detect(tolower(temp), "lips") |
      str_detect(tolower(temp), "girl") |
      str_detect(tolower(temp), "woman")
    ~ "female",
    TRUE ~ "no tag"
  )) |> 
  select(-parts_description) # get rid of parts_description column for bind_rows
```

```{r}
# Create new police dataframe with re-categorized gender (pilot2)
pilot2 <- pilot |> 
  filter(gender != "no tag") |> 
  mutate(temp="NA", gender2=gender) |> 
  bind_rows(pilot_notag)

# Scrape release_year
release_year <- map(pilot2$item_link, scrape_year)
release_year <- release_year |> 
  as.character() %>% 
  ifelse(. == "character(0)", "NA", .)

# Add release_year column to chef2 dataframe and convert to numeric
pilot2 <- pilot2 |> 
  mutate(release_year=release_year) |> 
  filter(release_year != "NA") |> 
  mutate(release_year=as.numeric(release_year)) |> 
  mutate(gender2=ifelse(release_year<1996, "male", gender2))

# Summarize counts and props by gender2 for graphing
pilot2_graph <- pilot2 |> 
  mutate(total=n()) |> 
  group_by(gender2) |> 
  summarize(count=n(),prop=round(count/total,2)) |> 
  distinct()
```

```{r}
# Bar chart of pilot2 counts
pl1 <- ggplot(pilot2_graph, aes(x = gender2, y = count, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Pilot Corrected",
    x = "Gender",
    y = "Count",
    fill = "Gender"
  ) +
  geom_text(aes(label = count)) +
  scale_fill_wbi()
pl1
pl1 <- add_logo(pl1)

# Bar chart of pilot2 proportions
pl2 <- ggplot(pilot2_graph, aes(x = gender2, y = prop, fill = gender2)) +
  geom_col(show.legend = FALSE) +
  labs(
    title = "Pilot Corrected",
    subtitle = paste("Out of", as.character(sum(pilot2_graph$count)), "total"),
    x = "Gender",
    y = "Proportion",
    fill = "Gender"
  ) +
  geom_text(aes(label = prop)) +
  scale_fill_wbi()
pl2
pl2 <- add_logo(pl2)

# Histogram of pilot2 counts
pl3 <- ggplot(pilot2, aes(x = release_year, fill=gender2)) +
  geom_histogram(show.legend = FALSE, binwidth = 5) +
  labs(
    title = "Distribution of Release Year by Gender for Pilot Minifigs",
    x = "Release Year",
    y = "Count",
    fill = "Gender"
  ) +
  facet_wrap(~gender2) +
  scale_fill_wbi()
pl3
pl3 <- add_logo(pl3)
```
