---
title: "scraping_2025"
output: html_document
date: "2025-06-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(purrr)
library(stringi)
library(plotrix)
source("scraping_func.R")
source("../wbi_colors.R")
source("../expression_gender.R")
```

```{r}
# check permission
robotstxt::paths_allowed(
  paths = c("https://www.bricklink.com/catalogItemInv.asp?S=10391-1&v=0&bt=0&sortBy=0&sortAsc=A")
)
```
## Pharrell Williams: Over the Moon 

```{r}
pharrell_parts <- rvest::read_html("https://www.bricklink.com/catalogItemInv.asp?S=10391-1&v=0&bt=0&sortBy=0&sortAsc=A")
```

```{r}
description <- pharrell_parts %>% 
  html_elements(".IV_ITEM td:nth-child(4)") %>% 
  html_text()

item_number <- pharrell_parts %>% 
  html_elements(".IV_ITEM td:nth-child(3)") %>% 
  html_text() %>% 
  str_trim()

link <- pharrell_parts %>% 
  html_elements(".IV_ITEM a:nth-child(1)") %>% 
  html_attr("href") %>% 
  paste0("https://www.bricklink.com", .)

qty <- pharrell_parts %>% 
  html_elements(".IV_ITEM td:nth-child(2)") %>% 
  html_text()
qty <- as.numeric(gsub("[^0-9]", "", qty))
       
# table format
pharrell_lists <- list(Description = description, ItemNo = item_number, Link = link, Quantity = qty)
pharrell_table <- as_tibble(pharrell_lists)
```

```{r}
# obtain minifigs in the set
pharrell_minifigs <- pharrell_table %>% 
  filter(grepl("3626", ItemNo)) 
  
pharrell_minifigs <- rbind(pharrell_minifigs, list("Medium Nougat Minifigure, Head Female Black Eyebrows, Eyes and Eyelashes, Reddish Brown Lips, Neutral Pattern", "3626pb3719", "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626pb3719&idColor=150", 1))

pharrell_minifigs <- rbind(pharrell_minifigs, list("Dark Orange Minifigure, Head Black Eyebrows, Reddish Brown Cheek Lines, Chin Dimple and Dots under Eyes, Neutral Pattern", "3626pb3718", "https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626pb3718&idColor=68", 1))
```

```{r}
# test <- map("https://www.bricklink.com/v2/catalog/catalogitem.page?P=3626pb3280&idColor=90#T=C&C=90", scrape_appearance)
pharrell_minifigs <- pharrell_minifigs %>% 
  mutate(NumberApp = map(pharrell_minifigs$Link, scrape_appearance)) %>% 
  mutate(NumberSets = str_extract(NumberApp, "\\d+"))

pharrell_minifigs <- pharrell_minifigs %>% 
  mutate(ColorID = case_when(str_sub(Link, -3, -3) == "="  ~ str_sub(Link, -2), 
                             str_sub(Link, -3, -3) != "=" ~ str_sub(Link, -3))) %>%
  mutate(PriceLink = paste0("https://www.bricklink.com/catalogPG.asp?P=", ItemNo, "&ColorID=", ColorID))

heads_prices <- map(pharrell_minifigs[1:4, ]$PriceLink, get_price) 
heads_prices_one <- map(pharrell_minifigs[5:8, ]$PriceLink, get_price)
heads_prices_two <- map(pharrell_minifigs[9:12, ]$PriceLink, get_price)
heads_prices_thr <- map(pharrell_minifigs[13:16, ]$PriceLink, get_price)
heads_prices_fou <- map(pharrell_minifigs[17:20, ]$PriceLink, get_price)
heads_prices_fiv <- map(pharrell_minifigs[21:24, ]$PriceLink, get_price)
heads_prices_six <- map(pharrell_minifigs[25:28, ]$PriceLink, get_price)
heads_prices_sev <- map(pharrell_minifigs[29:32, ]$PriceLink, get_price)
heads_prices_eig <- map(pharrell_minifigs[33:36, ]$PriceLink, get_price)
heads_prices_nin <- map(pharrell_minifigs[37:40, ]$PriceLink, get_price)
heads_prices_ten <- map(pharrell_minifigs[41:44, ]$PriceLink, get_price)
heads_prices_ele <- map(pharrell_minifigs[45:48, ]$PriceLink, get_price)
heads_prices_twe <- map(pharrell_minifigs[49:51, ]$PriceLink, get_price)

heads_prices_table$ItemNo <- pharrell_minifigs$ItemNo[1:4]
heads_prices_table_one$ItemNo <- pharrell_minifigs$ItemNo[5:8]
heads_prices_table_two$ItemNo <- pharrell_minifigs$ItemNo[9:12]
heads_prices_table_thr$ItemNo <- pharrell_minifigs$ItemNo[13:16]
heads_prices_table_fou$ItemNo <- pharrell_minifigs$ItemNo[17:20]
heads_prices_table_fiv$ItemNo <- pharrell_minifigs$ItemNo[21:24]
heads_prices_table_six$ItemNo <- pharrell_minifigs$ItemNo[25:28]
heads_prices_table_sev$ItemNo <- pharrell_minifigs$ItemNo[29:32]
heads_prices_table_eig$ItemNo <- pharrell_minifigs$ItemNo[33:36]
heads_prices_table_nin$ItemNo <- pharrell_minifigs$ItemNo[37:40]
heads_prices_table_ten$ItemNo <- pharrell_minifigs$ItemNo[41:44]
heads_prices_table_ele$ItemNo <- pharrell_minifigs$ItemNo[45:48]
heads_prices_table_twe$ItemNo <- pharrell_minifigs$ItemNo[49:51]

heads_prices_table <- heads_prices |>
  plyr::ldply(bind_rows)
heads_prices_table_one <- heads_prices_one |>
  plyr::ldply(bind_rows)
heads_prices_table_two <- heads_prices_two |>
  plyr::ldply(bind_rows)
heads_prices_table_thr <- heads_prices_thr |>
  plyr::ldply(bind_rows)
heads_prices_table_fou <- heads_prices_fou |>
  plyr::ldply(bind_rows)
heads_prices_table_fiv <- heads_prices_fiv |>
  plyr::ldply(bind_rows)
heads_prices_table_six <- heads_prices_six |>
  plyr::ldply(bind_rows)
heads_prices_table_sev <- heads_prices_sev |>
  plyr::ldply(bind_rows)
heads_prices_table_eig <- heads_prices_eig |>
  plyr::ldply(bind_rows)
heads_prices_table_nin <- heads_prices_nin |>
  plyr::ldply(bind_rows)
heads_prices_table_ten <- heads_prices_ten |>
  plyr::ldply(bind_rows)
heads_prices_table_ele <- heads_prices_ele |>
  plyr::ldply(bind_rows)
heads_prices_table_twe <- heads_prices_twe |>
  plyr::ldply(bind_rows)

data_prices_pharrell <- list(heads_prices_table, heads_prices_table_two, heads_prices_table_one, heads_prices_table_thr, heads_prices_table_fou, heads_prices_table_fiv, heads_prices_table_six, heads_prices_table_sev, heads_prices_table_eig, heads_prices_table_nin, heads_prices_table_ten, heads_prices_table_ele, heads_prices_table_twe) %>%
  plyr::ldply(rbind)

pharrell_full_price <-left_join(pharrell_minifigs, data_prices_pharrell, by = "ItemNo") %>% 
  select(!NumberApp)

write.csv(pharrell_full_price, file = "pharrell_price.csv")

```

# Color Catalogue

```{r}
color_page <- rvest::read_html("https://www.bricklink.com/catalogColors.asp")

ID <- color_page %>% 
  html_elements("tr+ tr td:nth-child(1) font") %>% 
  html_text() %>% 
  str_trim

Name <- color_page %>% 
  html_elements("tr+ tr td:nth-child(4) font") %>% 
  html_text() %>% 
  str_trim

Year <- color_page %>% 
  html_elements("tr+ tr td:nth-child(9) font") %>% 
  html_text() %>% 
  str_trim()

Parts <- color_page %>% 
  html_elements("tr+ tr td:nth-child(5) font") %>% 
  html_text() %>% 
  str_trim()

Sets <- color_page %>% 
  html_elements("tr+ tr td:nth-child(6) font") %>% 
  html_text() %>% 
  str_trim()

# table format
color_lists <- list(ID = ID, Name = Name, Year = Year, Parts = Parts, Sets = Sets)
color_table <- as_tibble(color_lists)

color_table <- color_table %>% 
  mutate(link = paste0("https://www.bricklink.com/catalogList.asp?v=2&colorID=", ID))

color_table_ID <- color_table %>% 
  select(ID, Name)

write.csv(color_table, file = "color_table.csv")
color_table <- read.csv("color_table.csv")
```


## Update of Minifigs Head (2022-2024)
```{r}
# link of 2022-2024
links_year <- c("https://www.bricklink.com/catalogList.asp?itemYear=2022&catString=238&catType=P", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2023&catString=238&catType=P", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2024&catString=238&catType=P")

pages_year <- map(links_year, get_pages_year)

links_all <- map2(pages_year, links_year, generate_page_links)

years <- c("2022", "2023", "2024")
new_year_data <- tibble(category = years, link = links_all, num_pages = unlist(pages_year)) |>
  tidyr::unnest(cols = c(link)) |>
  dplyr::mutate(link = as.character(link))

write.csv(new_year_data, file = "new_years.csv")

# worked to scrape data (quota limit doesn't apply??)
data_new <- purrr::map2(new_year_data$link, new_year_data$category, scrape_minifigs_data)
data_bind <- plyr::ldply(data_new, rbind)
write.csv(data_bind, file = "minifigs_heads_2025.csv")


data_bind <- read.csv("minifigs_heads_2025.csv")
data_bind <- data_bind |>
  mutate(item_link = paste0("https://bricklink.com/v2/catalog/catalogitem.page?P=", item_number),
         minifigs_link = paste0("https://www.bricklink.com/catalogItemIn.asp?P=", item_number, "&in=M"))

new_human_heads <- data_bind %>% 
  filter(!grepl("Alien|Skull|Balaclava|Clown|Baby|Robot|without Face|Statue|Green Eyes|SW|Joker|Pumpkin|Face Paint|Green Cheek|Metallic|Magenta|Fangs|Silver Face|Azure Eyes|Fur|Pixelated|Electricity|Gills", description))

# Vector to store scraped minifigure ids (no description for the whole minifig)
#mini_info <- map(new_human_heads$minifigs_link, scrape_mini_id)

# Add minifig ids to sets_data and unnest so that each row is a minifig
#new_human_heads <- new_human_heads |>
#  mutate(mini_id = mini_info) |>
#  unnest(cols = mini_id)

# Add parts_link for each minifig
# new_human_heads <- new_human_heads %>% 
#   mutate(
#     parts_link = paste0("https://www.bricklink.com/catalogItemInv.asp?M=", mini_id),
#     minifig_link = paste0("https://www.bricklink.com/v2/catalog/catalogitem.page?M=", mini_id),
#     color_link = paste0(item_link, "#T=C"))

#mini_description <- map(new_human_heads$minifig_link, scrape_mini_description)

new_human_heads <- new_human_heads %>% 
  mutate(color_link = paste0(item_link, "#T=C"),
         color = map(color_link, scrape_color))

new_human_heads_unnested <- new_human_heads %>% 
  unnest(color) %>% 
  rename(Name = color)

new_human_heads_color <- new_human_heads_unnested %>%
  filter(!grepl("Azure|Lavender|Trans|White|Blue|Black|Green|Lime|Gold|Dark Tan|Orange|Umber|View|Not|Light Brown", Name)) %>% 
  filter(Name != "character(0)")

heads_flesh_new <- new_human_heads_color %>% 
  left_join(color_table_ID, by = "Name")

heads_flesh_new <- heads_flesh_new %>% 
  mutate(PriceLink = paste0("https://www.bricklink.com/catalogPG.asp?P=", item_number, "&ColorID=", ID))

flesh_hex_table <- tibble(Name = skin_colors, hexCode = skin_tones)

heads_flesh_new <- heads_flesh_new[!duplicated(heads_flesh_new[, "item_number"]), ] %>% 
  left_join(flesh_hex_table, by = "Name")

write.csv(heads_flesh_new, "heads_flesh_unique.csv")
heads_flesh_new <- read.csv("heads_flesh_unique.csv")
table(heads_flesh_new$Name)

color_skin_summary <- heads_flesh_new %>%
  group_by(Name, category, ID, hexCode) %>%
  summarise(count = n()) %>% 
  mutate(spectrum = case_when(Name == "Yellow" ~ 1,
                              Name == "Light Nougat" ~ 2,
                              Name == "Nougat" ~ 3,
                              Name == "Tan" ~ 4,
                              Name == "Medium Tan" ~ 5,
                              Name == "Medium Nougat" ~ 6,
                              Name == "Medium Brown" ~ 7,
                              Name == "Sienna" ~ 8,
                              Name == "Reddish Brown" ~ 9))

color_skin_sum_wide <- color_skin_summary %>% 
  pivot_wider(names_from = category, values_from = count, values_fill =0) %>% 
  mutate(total = sum(`2022`, `2023`, `2024`))
```

## Update of Minifigs Head (2003-2021)
```{r}
links_year <- c("https://www.bricklink.com/catalogList.asp?itemYear=2003&catString=238&catType=P", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2004&catString=238&catType=P", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2005&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2006&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2007&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2008&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2009&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2010&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2011&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2012&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2013&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2014&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2015&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2016&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2017&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2018&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2019&catString=238&catType=P",
                "https://www.bricklink.com/catalogList.asp?itemYear=2020&catString=238&catType=P", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2021&catString=238&catType=P")

pages_year <- map(links_year, get_pages_year)

links_all <- map2(pages_year, links_year, generate_page_links)

years <- c("2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021")
new_year_data <- tibble(category = years, link = links_all, num_pages = unlist(pages_year)) |>
  tidyr::unnest(cols = c(link)) |>
  dplyr::mutate(link = as.character(link))


# worked to scrape data (quota limit doesn't apply??)
data_new <- purrr::map2(new_year_data$link, new_year_data$category, scrape_minifigs_data)
data_bind <- plyr::ldply(data_new, rbind)

data_bind <- data_bind |>
  mutate(item_link = paste0("https://bricklink.com/v2/catalog/catalogitem.page?P=", item_number),
         minifigs_link = paste0("https://www.bricklink.com/catalogItemIn.asp?P=", item_number, "&in=M"))

new_human_heads_old <- data_bind %>% 
  filter(!grepl("Alien|Skull|Balaclava|Clown|Baby|Robot|without Face|Statue|Green Eyes|SW|Joker|Pumpkin|Face Paint|Green Cheek|Metallic|Magenta|Fangs|Silver Face|Azure Eyes|Fur|Pixelated|Electricity|Gills", description))

new_human_heads_old <- new_human_heads_old %>% 
  mutate(color_link = paste0(item_link, "#T=C"),
         color = map(color_link, scrape_color))

new_human_heads_unnested_old <- new_human_heads_old %>% 
  unnest(color) %>% 
  rename(Name = color)

new_human_heads_color_old <- new_human_heads_unnested_old %>%
  filter(!grepl("Azure|Lavender|Trans|White|Blue|Black|Green|Lime|Gold|Dark Tan|Orange|Umber|View|Not|Grey|Silver|Aqua", Name)) %>% 
  filter(Name != "character(0)")

heads_flesh_old <- new_human_heads_color_old %>% 
  left_join(color_table_ID, by = "Name")

heads_flesh_old <- heads_flesh_old %>% 
  mutate(PriceLink = paste0("https://www.bricklink.com/catalogPG.asp?P=", item_number, "&ColorID=", ID))

heads_flesh_old <- heads_flesh_old[!duplicated(heads_flesh_old[, "item_number"]), ] %>% 
  left_join(flesh_hex_table, by = "Name")

heads_flesh_new_standard <- subset(heads_flesh_new, select = -c(X.1, X))

heads_flesh_old <- heads_flesh_old %>% 
   mutate(gender = case_when(
     str_detect(tolower(description), paste(male_keywords, collapse = "|"))
    ~ "male",
    str_detect(tolower(description), paste(female_keywords, collapse = "|"))
    ~ "female",
    TRUE ~ "no tag"),
    age = case_when(
    str_detect(tolower(description), paste(child, collapse = "|"))
    ~ "child",
    str_detect(tolower(description), paste(old, collapse = "|"))
    ~ "old",
    TRUE ~ "no tag"))

heads_flesh_old <- heads_flesh_old %>% 
  mutate(expression = sub(".*,", "", description))
```


```{r}
heads_flesh_new <- heads_flesh_new %>% 
   mutate(gender = case_when(
     str_detect(tolower(description), paste(female_keywords, collapse = "|"))
    ~ "female",
     str_detect(tolower(description), paste(male_keywords, collapse = "|"))
    ~ "male",
    TRUE ~ "no tag"),
    age = case_when(
    str_detect(tolower(description), paste(child, collapse = "|"))
    ~ "child",
    str_detect(tolower(description), paste(old, collapse = "|"))
    ~ "old",
    TRUE ~ "no tag"))

heads_flesh_new <- heads_flesh_new %>% 
  mutate(expression = sub(".*,", "", description))

write.csv(heads_flesh_new, "heads_updated.csv")
heads_flesh_new %>% group_by(gender) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total))
```

```{r}
#merge 
heads_total <- rbind(heads_flesh_old, heads_flesh_new_standard)

write.csv(heads_total, "heads_total.csv")

summary_total <- heads_total %>% group_by(Name, gender) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total))

heads_total %>% filter(Name == "Reddish Brown") %>% 
  select(item_number, item_link, gender, category, description)
```


```{r}
update_heads <- color_skin_sum_wide %>% 
  ggplot(aes(x = reorder(Name, -total), y = total, fill = Name)) +
  geom_col(show.legend = FALSE) +
  coord_flip() +
  scale_fill_skintones() + 
  labs(title = "Distribution of Flesh Tones of Minifigurine Heads (2022-2024)",
       x = "Flesh Tones",
       y = "Count") +
   geom_text(aes(label =total), hjust = 1.5, fontface = "bold")

color_skin_summary %>% 
  ggplot(aes(x = category, y = count, fill = Name)) +
  geom_col(color = "black", linewidth = 0.1) +
  scale_fill_skintones() + 
  labs(title = "Distribution of Flesh Tones of Minifigurine Heads by Year(2022-2024)",
       x = "Flesh Tones",
       y = "Count")

color_skin_summary %>% 
  ggplot(aes(x = category, y = count, fill = reorder(Name, -spectrum))) +
  geom_col(color = "black", linewidth = 0.1, width = 0.6) +
  scale_fill_skintones() + 
  labs(title = "Distribution of Flesh Tones of Minifigurine Heads by Year(2022-2024)",
       x = "Flesh Tones",
       y = "Count",
       fill = "Flesh Tone Names") +
   geom_text(aes(label = case_when((count > 5) ~ count,
                                   (count <= 5) ~ NA)),
    position = position_stack(vjust = 1),
    vjust = 1.5,
    color = "white",
    fontface = "bold")

pie(x = color_skin_sum_wide$total, labels = color_skin_sum_wide$total, 
    main="Distribution of Flesh Tones of Minifigurine Heads (2022-2024)", 
    col = color_skin_sum_wide$hexCode, radius = 1) +legend("topright", legend = color_skin_sum_wide$Name, cex = 0.8, 
           fill = color_skin_sum_wide$hexCode)

pie(x = color_skin_sum_wide$total, labels = paste0(color_skin_sum_wide$Name, "\n", color_skin_sum_wide$total), 
    main="Distribution of Flesh Tones of Minifigurine Heads (2022-2024)", 
    col = color_skin_sum_wide$hexCode, radius = 1)

par(mfrow = c(1, 3))
pie(x = color_skin_sum_wide$`2022`, labels = "",
    main="2022", 
    col = color_skin_sum_wide$hexCode, radius = 1) 
pie(x = color_skin_sum_wide$`2023`, labels = "",
    main="2023", 
    col = color_skin_sum_wide$hexCode, radius = 1) 
pie(x = color_skin_sum_wide$`2024`, labels = "",
    main="2024", 
    col = color_skin_sum_wide$hexCode, radius = 1)
par(mfrow = c(1, 1))
legend(x = -1.2, y = -1.2, legend = color_skin_sum_wide$Name, cex = 0.5, 
           fill = color_skin_sum_wide$hexCode, ncol = 5)

color_skin_summary %>% 
  ggplot(aes(x = category, y = count, fill = reorder(Name, -spectrum))) +
  geom_area(show.legend = FALSE) +
  scale_fill_skintones() + 
  labs(title = "Distribution of Flesh Tones of Minifigurine Heads (2022-2024)",
       x = "Flesh Tones",
       y = "Count")
```

```{r}
ggsave(update_heads, 
       filename = "update_heads.pdf",
       device = "pdf",
       height = 4, width = 7, units = "in")

color_skin_sum_wide %>% 
  filter(!grepl("Light Nougat|Yellow", Name)) %>% 
  summarise(total_num = sum(total))
```



```{r}
heads_subset <- heads_flesh_new[1:20, ]
data_sub_heads <- map_dfr(heads_subset$PriceLink, get_price_one)

heads_prices_new <- map(heads_flesh_new$PriceLink, get_price_one) 

heads_prices_new <- heads_prices_new |>
  plyr::ldply(bind_rows)
```
 
```{r}
#facial expression
heads_flesh_new <- heads_flesh_new %>% 
  mutate(facialApp = sapply(expression, function(char) str_count(description, fixed(char)))) %>% 
  pivot_longer(
    cols = starts_with("facialApp"),
    names_to = "expression",
    names_prefix = "facialApp",
    values_to = "app")
```
 
 
```{r}
# merge datasets to make complete minifigs heads data
```
 
## Update of Minifigs (2022-2024) Copy but not just Heads

```{r}
# link of 2022-2024
links_heads_year <- c("https://www.bricklink.com/catalogList.asp?itemYear=2022&catType=M", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2023&catType=M", 
                "https://www.bricklink.com/catalogList.asp?itemYear=2024&catType=M")

pages_heads_year <- map(links_heads_year, get_pages)

links_heads_all <- map2(pages_heads_year, links_heads_year, generate_page_links)

new_minifigs_data <- tibble(category = years, link = links_heads_all, num_pages = unlist(pages_heads_year)) |>
  tidyr::unnest(cols = c(link)) |>
  dplyr::mutate(link = as.character(link))

write.csv(new_minifigs_data, file = "new_minifigs.csv")

print(sum(as.numeric(new_minifigs_data$num_pages)))

# yep definitely too big for quota, splitting category data
categories_subset <- new_minifigs_data[1:20, ]
data_sub <- purrr::map2(categories_subset$link, categories_subset$category, scrape_minifigs_data)
data_bind_s <- plyr::ldply(data_sub, rbind)

categories_subset2 <- new_minifigs_data[21:40, ]
data_sub2 <- purrr::map2(categories_subset2$link, categories_subset2$category, scrape_minifigs_data)
data_bind_s2 <- plyr::ldply(data_sub2, rbind)

categories_subset3 <- new_minifigs_data[41:60, ]
data_sub3 <- purrr::map2(categories_subset3$link, categories_subset3$category, scrape_minifigs_data)
data_bind_s3 <- plyr::ldply(data_sub3, rbind)

categories_subset4 <- new_minifigs_data[61:64, ]
data_sub4 <- purrr::map2(categories_subset4$link, categories_subset4$category, scrape_minifigs_data)
data_bind_s4 <- plyr::ldply(data_sub4, rbind)

data_all_minifigs_new <- list(data_bind_s, data_bind_s2, data_bind_s3, data_bind_s4) |>
  plyr::ldply(rbind)
```
```{r}
# add links to each item to minifigs data
data_all_minifigs_new <- data_all_minifigs_new |>
  mutate(item_link = paste0("https://bricklink.com/v2/catalog/catalogitem.page?M=", item_number))

write_csv(data_all_minifigs_new, "minifigs_full_data_2025.csv")
minifigs_data <- read_csv("../data/minifigs_data.csv")

#bind tables (up until 2024)
#category and year are in one column (fix that later??)
minifigs_data_2025 <- unique(rbind(data_all_minifigs_new, minifigs_data))
```


