---
title: "bdp_series"
output: html_document
date: "2025-07-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(purrr)
library(stringi)
library(plotrix)
library(gridExtra)
library(insight)
library(cowplot)
source("../minifigs/scraping_func.R")
source("../wbi_colors.R")
```

```{r}
bdp_og <- read.csv("BDP.csv")
```

```{r}
bdp_og <- bdp_og %>% 
  mutate(gender_diff = Male.coded - Female.coded) %>% 
  slice(1:40)

bdp_grpd <- bdp_og %>% 
  group_by(N) %>% 
  summarise(female = sum(Female.coded, na.rm = TRUE),
            male = sum(Male.coded, na.rm = TRUE),
            diff_total = sum(gender_diff, na.rm=TRUE),
            avg_age = mean(Age)) 

bdp_grpd %>%  
  ggplot(aes(y = diff_total, x = factor(N))) +
  geom_col(aes(fill = factor(N))) +
  scale_fill_wbi() +
  labs(title = "F/M-coded Minifig Difference in Each Set Featured in BDP (Series 1-8)",
       x = "Series",
       y = "Difference", 
       fill = "Series") +
   geom_text(aes(label = paste0("M - ", male, "\n F - ", female), vjust = 0.5), 
             color = "#300000")

bdp_long <- bdp_grpd %>% 
  pivot_longer(cols = ends_with("ale"), names_to = "gender", 
               values_to = "count_by_gender", values_drop_na = TRUE) %>% 
  mutate(gender_code = case_when(gender == "male" ~ "Male-coded",
                                 gender == "female" ~ "Female-coded"))

gender_series <- bdp_long %>%  
  ggplot(aes(y = count_by_gender, x = factor(N), fill = gender_code)) +
  geom_col(position = position_dodge(width = 0.9)) +
  scale_fill_wbi() +
  labs(title = "F/M-coded Minifig Difference in Each Set Featured in BDP (Series 1-8)",
       x = "Series",
       y = "Count of Minifigs", 
       fill = "Gender") +
   geom_text(aes(label = count_by_gender), 
             position= position_dodge(width=0.9),
             vjust = -0.2,
             color = "black")
```

```{r}
bdp_og %>% group_by(Gender) %>% summarise(n())
```

```{r}
bdp_sliced <- bdp_grpd %>% 
  drop_na(avg_age) %>% 
  mutate(age_diff = avg_age-34.58)

age <- bdp_sliced %>%  
  ggplot(aes(y = age_diff, x = factor(N))) +
  geom_col(aes(fill = factor(N)), width = 0.5) +
  geom_hline(aes(yintercept = 0), linetype = "dashed", 
             color = "#b97295", size = 1, show.legend = TRUE) +
  scale_fill_wbi() +
  labs(title = "Average Age of Final 5 Designers in BDP (Series 1-4)",
       x = "Series",
       y = "Age", 
       fill = "Series") +
   geom_text(aes(label = avg_age, vjust = 1.2), 
             color = "black") +
  theme(axis.text.y = element_blank()) +
  annotate("text", x = 0.75, y = -0.08, label = "Aggregate", size = 4.5, color = "#b97295") +
  annotate("text", x = 4.45, y = -0.08, label = "34.58", size = 4.5, color = "#b97295")
```

```{r}
bdp_og <- bdp_og %>% 
  mutate(difference = Male.coded - Female.coded)

bdp_diff <- bdp_og[!is.na(bdp_og$difference), ]
bdp_diff <-  tibble::rowid_to_column(bdp_diff, "row_id")
bdp_diff <- bdp_diff %>% 
  mutate(diff_split = case_when(difference == 1 ~ "+1 male-coded",
                                difference == 0 ~ "equal",
                                difference < 0 ~ "male < female-coded", 
                                TRUE ~ "> +1 male-coded"))

bdp_diff %>%  
  ggplot(aes(x = factor(diff_split), fill = factor(diff_split))) +
  geom_bar() +
  scale_fill_wbi() +
  ylim(0, 20) +
  labs(title = "BDP Set Inspiration and Setting (Series 1-5)",
       x = "Inspiration",
       y = "Count of Sets") +
  theme_minimal()

diff_graph <- bdp_diff %>% 
  ggplot(aes(y = difference, x = row_id)) +
  geom_area(alpha = 1/2, fill = "#8cc63f") +
  stat_smooth(
        geom = 'area', method = 'loess', span = 1/6,
        alpha = 1/2, fill = "#f43b93") +
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), axis.ticks.x = element_blank()) +
  labs(title = "Margin between Male-coded and Female-coded Minifigures in BDP (Series 1-8)",
       y = "Male - Female (coded)")

add_logo(diff_graph)

bdp_diff %>% 
  group_by(diff_split) %>% 
  summarise(count = n())
  
```


```{r}
category <- read.csv("BDP_category.csv")

category <- category[1:25, ]

inspire <- category %>%  
  ggplot(aes(x = factor(Inspiration.coded), fill = Setting)) +
  geom_bar(width = 0.5) +
  scale_fill_wbi() +
  ylim(0, 8) +
  labs(title = "BDP Set Inspiration and Setting (Series 1-5)",
       x = "Inspiration",
       y = "Count of Sets", 
       fill = "Setting") +
  theme_minimal()

add_logo(inspire)
```


```{r}
ggsave(gender_series, 
       filename = "gender_series.pdf",
       device = "pdf",
       height = 4, width = 7, units = "in")

ggsave(age, 
       filename = "age.pdf",
       device = "pdf",
       height = 4, width = 7, units = "in")
```


```{r}
happy <- c(3, 7, 12,
2, 3, 11,
4, 5, 11,
2, 7, 11,
5, 9, 11,
3, 7,
2, 8, 11,
3, 7, 11,
5, 11, 12,
3, 7, 11,
1, 2, 4,
1, 7, 10,
3, 7, 11,
3, 5, 7,
3, 6, 11,
3, 6, 11,
3, 7, 8,
3, 11, 12,
2, 3, 7,
2, 9, 11,
1, 4, 8,
1, 7, 11,
3, 4, 7,
3, 7, 11,
4, 7, 8,
2, 3, 7,
1, 4, 8,
3, 6, 7,
7, 11,
7, 8, 11,
6, 7, 11)

sad <- c(2, 5, 6,
3, 7, 9,
1, 6, 11,
2, 3, 9,
2, 6, 10,
6, 11,
4, 6,
3, 4, 11,
3, 6, 11,
2, 6, 9,
6, 9,
1, 6, 10,
4, 6, 10,
7, 8, 10,
1, 3, 6,
2, 9, 11,
4, 10, 11,
6, 10,
6, 9, 11,
4, 7, 11,
2, 5, 9,
3, 11,
2, 3, 9,
2, 5, 9,
3, 4, 6,
4, 6, 11,
2, 4, 11,
2, 8,
6, 8, 11,
2, 6, 9)

neutral <- c(1, 4, 7,
2, 6, 10,
1, 7, 9,
2, 3, 4,
3, 9, 11,
1, 6, 8,
7, 8, 10,
7, 8, 10,
7, 10, 12,
4, 7,
4, 11, 12,
4, 9, 11,
7, 9, 10,
4, 8,
2, 3, 7,
4, 8, 11,
1, 4, 8,
4, 6, 10,
7,
6, 7, 10,
2, 5, 6,
6, 8, 10,
5, 10,
2, 4, 12,
5, 8, 10,
4, 7, 10,
6, 9, 10,
2, 5, 11,
1, 10,
1, 7, 10,
4, 7, 8)

excited <- c(2, 5, 10,
5, 9, 10,
1, 7, 8,
5, 7, 10,
1, 4, 10,
1, 10, 11,
5, 10, 11,
5, 7, 11,
1, 5, 7,
2, 10, 11,
4,
1, 5, 10,
1, 5, 6,
2, 5,
6, 12,
2, 4, 5,
1, 5, 10,
1, 5, 10,
5, 6, 12,
1, 5, 7,
3, 6, 7,
4, 7, 10,
4, 5,
4, 8, 10,
2, 4, 6,
1, 5, 8,
5, 7, 12,
2, 4, 5,
3, 5, 11,
1, 5, 10,
5, 8, 11)

glasses <- c(1, 9, 10,
4, 6, 9,
6, 7, 10,
4, 8, 10,
1, 10, 11,
1, 6, 10,
2, 10,
1, 4, 10,
7, 10, 12,
1, 4, 7,
2, 8, 12,
1, 6,
6, 10, 12,
2, 10,
1, 9, 10,
9, 10, 11,
7, 9, 10,
6, 9, 10,
2, 6, 10,
2, 7, 10,
1, 3, 10,
5, 6, 9,
10,
2, 3, 10,
5, 7, 11,
8, 9, 10,
6, 10, 12,
2, 7, 12,
2, 10,
1, 9, 10,
1, 8, 10)
  
sad_table <- as.data.frame(sad)
happy_table <-as.data.frame(happy)
neutral_table <- as.data.frame(neutral)
excited_table <- as.data.frame(excited)
glasses_table <- as.data.frame(glasses)

library(DescTools)

sad_table %>% 
  group_by(sad) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

happy_table %>% 
  group_by(happy) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

neutral_table %>% 
  group_by(neutral) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

excited_table %>% 
  group_by(excited) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

glasses_table %>% 
  group_by(glasses) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
```

